import * as B from "file:///Users/chuah/Documents/ChatGPT/bendex/bend/bend2/bend.ts";
import * as Safe from "file:///Users/chuah/Documents/ChatGPT/bendex/bend/bend2/safe.ts";
import * as fs from "node:fs";
import * as crypto from "node:crypto";
const entry=process.argv.slice(3).find(a=>!a.startsWith("--"))||new URL("../src/campfire_authority_proof.bend", import.meta.url).pathname;
const dir=process.argv[2];
if(!dir)throw Error("Fresh output directory required");
const roots=["campfire_authority_laws:refused_tick_preserves_whole_owner", "campfire_authority_laws:refused_placement_preserves_owner_and_held_item", "campfire_authority_laws:absent_recipe_preserves_owner_and_held_item", "campfire_authority_laws:creative_placement_preserves_complete_held_input", "campfire_authority_laws:placed_cell_contains_exactly_one_complete_key", "campfire_authority_laws:disabled_result_preserves_slot_for_retry", "campfire_authority_laws:enabled_drop_clears_input_but_preserves_timer_words", "campfire_authority_laws:missing_recipe_drops_complete_original_stack", "campfire_authority_laws:nonpositive_cooldown_does_not_change_timer_word", "campfire_authority_laws:lit_signed_overflow_does_not_use_unsigned_completion", "campfire_authority_laws:snapshot_retains_complete_actual_owner", "campfire_authority_laws:refused_load_preserves_complete_actual_owner", "campfire_authority_laws:removal_after_clear_cannot_emit_duplicate_items", "campfire_authority_laws:ticker_replacement_resets_ephemeral_recipe_cache", "campfire_authority_laws:first_empty_slot_has_lowest_placement_priority"];
const allRoots=roots;
const selectedRoots=roots.filter(k=>!k.endsWith(":lit_signed_overflow_does_not_use_unsigned_completion"));
const sha=x=>crypto.createHash("sha256").update(x).digest("hex");
const book=B.book_nil(),seen=new Map();
await B.book_load(book,entry,"",seen);
const before=Object.fromEntries([...seen.keys()].sort().map(p=>[p,sha(fs.readFileSync(p))]));
B.book_valid(book);
if(book.hols!==0)throw Error("Open proof holes");
const originalOrder=[...book.order],originalTlds=book.tlds,originalCtrs=book.ctrs,originalTmps=book.tmps;
const originals=Object.entries(book.tlds).map(([k,t])=>[k,t,t.T,t.$==="Def"?t.v:null,t.$==="Def"?t.e:null]);
const termPins=selectedRoots.map(k=>{const t=book.tlds[k];if(t?.$!=="Def"||!t.e||!t.v||t.u||t.i)throw Error("Missing checked pure proof "+k);return {name:k,type_sha256:sha(B.term_key(B.term_lower(t.T))),checked_proof_sha256:sha(B.term_key(t.e)),source_body_sha256:sha(B.term_key(B.term_lower(t.v)))};});
book.order=originalOrder.filter((k,i)=>selectedRoots.includes(k)&&originalOrder.lastIndexOf(k)===i);
if(book.order.length!==selectedRoots.length||book.tlds!==originalTlds||book.ctrs!==originalCtrs||book.tmps!==originalTmps)throw Error("Selection changed declaration ownership");
for(const [k,t,T,v,e] of originals)if(book.tlds[k]!==t||t.T!==T||(t.$==="Def"&&(t.v!==v||t.e!==e)))throw Error("Selection altered term "+k);
const manifest={entry,roots:selectedRoots,ordinary_roots:allRoots,omitted_root_boundary:"lit_signed_overflow_does_not_use_unsigned_completion: kernel rejects transitive actual json.encode_go affine live-code descent; covered by actual Java/native observation",original_root_count:originalOrder.length,selected_root_count:book.order.length,checked_types_and_bodies_unchanged:true,all_original_tlds_ctrs_tmps_retained:true,term_pins:termPins,source_files:[...seen.keys()],ordinary_source_api_check_passed:true};
fs.writeFileSync(dir+"/selection.json",JSON.stringify(manifest,null,2)+"\n");
console.log(JSON.stringify({phase:"checked-root-selection",roots,original_root_count:originalOrder.length}));
const exclusions=Safe.safe_emit(book,dir+"/selected.bendtt");
fs.writeFileSync(dir+"/scope.json",JSON.stringify({exclusions},null,2)+"\n");
console.log(JSON.stringify({phase:"export-complete",bytes:fs.statSync(dir+"/selected.bendtt").size,exclusions}));
if(exclusions.length)process.exitCode=2;

const after=Object.fromEntries([...seen.keys()].sort().map(p=>[p,sha(fs.readFileSync(p))]));
if(JSON.stringify(before)!==JSON.stringify(after))throw Error("Proof source changed during check/export");
fs.writeFileSync(dir+"/source-pins.json",JSON.stringify(after,null,2)+"\n");
