import * as B from "file:///Users/chuah/Documents/ChatGPT/bendex/bend/bend2/bend.ts";
process.on('uncaughtException',e=>{console.error(e?.$==='Err'?B.err_show(e):e);process.exit(1)});
import * as Safe from "file:///Users/chuah/Documents/ChatGPT/bendex/bend/bend2/safe.ts";
import * as fs from "node:fs";import * as crypto from "node:crypto";
const root=process.argv[2],dir=root+"/build/cooking-effect-geometry-proof";
const entry=root+"/src/cooking_effect_geometry_proof.bend";
const allRoots=[...fs.readFileSync(root+"/src/cooking_effect_geometry_laws.bend","utf8").matchAll(/^law (\w+):/gm)].map(m=>"cooking_effect_geometry_laws:"+m[1]);
const ordinaryOnly=["cooking_effect_geometry_laws:refused_capture_returns_both_complete_affine_owners"];
const roots=allRoots.filter(x=>!ordinaryOnly.includes(x));
const sha=x=>crypto.createHash("sha256").update(x).digest("hex");
const book=B.book_nil(),seen=new Map();await B.book_load(book,entry,"",seen);
const before=Object.fromEntries([...seen.keys()].sort().map(p=>[p,sha(fs.readFileSync(p))]));
B.book_valid(book);if(book.hols!==0)throw Error("Open proof holes");
console.log("ALL ORDINARY SOURCE CHECKS PASS");
const order=[...book.order],tlds=book.tlds,ctrs=book.ctrs,tmps=book.tmps;
const originals=Object.entries(tlds).map(([k,t])=>[k,t,t.T,t.$==="Def"?t.v:null,t.$==="Def"?t.e:null]);
const termPins=roots.map(k=>{const t=tlds[k];if(t?.$!=="Def"||!t.e||!t.v||t.u||t.i)throw Error("Missing checked pure proof "+k);return {name:k,type_sha256:sha(B.term_key(B.term_lower(t.T))),checked_proof_sha256:sha(B.term_key(t.e)),source_body_sha256:sha(B.term_key(B.term_lower(t.v)))};});
book.order=order.filter((k,i)=>roots.includes(k)&&order.lastIndexOf(k)===i);
if(book.order.length!==roots.length||book.tlds!==tlds||book.ctrs!==ctrs||book.tmps!==tmps)throw Error("Selection changed declaration ownership");
for(const [k,t,T,v,e] of originals)if(book.tlds[k]!==t||t.T!==T||(t.$==="Def"&&(t.v!==v||t.e!==e)))throw Error("Selection altered term "+k);
const exclusions=Safe.safe_emit(book,dir+"/selected.bendtt");
const after=Object.fromEntries([...seen.keys()].sort().map(p=>[p,sha(fs.readFileSync(p))]));
if(JSON.stringify(before)!==JSON.stringify(after))throw Error("Proof sources changed");
fs.writeFileSync(dir+"/selection.json",JSON.stringify({roots,termPins,exclusions,ordinary_only_roots:ordinaryOnly,checked_types_and_bodies_unchanged:true,all_original_declaration_maps_retained:true,source_pins:after},null,2)+"\n");
if(exclusions.length)throw Error("Export exclusions "+JSON.stringify(exclusions));
console.log("CHECKED ROOT EXPORT PASS");
