import * as B from "file:///Users/chuah/Documents/ChatGPT/bendex/bend/bend2/bend.ts";
import * as Safe from "file:///Users/chuah/Documents/ChatGPT/bendex/bend/bend2/safe.ts";
import * as fs from "node:fs";
import * as crypto from "node:crypto";
const entry=process.argv.slice(3).find(a=>!a.startsWith("--"))||new URL("../src/item_entity_pickup_proof.bend", import.meta.url).pathname;
process.on("uncaughtException",e=>{console.error(e?.$==="Err"?B.err_show(e):e);process.exit(1)});
const dir=process.argv[2];
if(!dir)throw Error("Fresh output directory required");
const roots=["item_entity_pickup_laws:refused_candidate_retains_both_complete_affine_owners", "item_entity_pickup_laws:client_side_item_receiver_is_inactive", "item_entity_pickup_laws:partial_survival_insertion_retains_residue_without_take_or_stats", "item_entity_pickup_laws:discarded_item_retains_original_count_and_nonpickup_fields", "item_entity_pickup_laws:survival_no_progress_keeps_residue_and_false_return", "item_entity_pickup_laws:creative_no_progress_clears_residue_and_returns_true", "item_entity_pickup_laws:unresolved_thrower_refuses_success_publication", "item_entity_pickup_laws:absent_thrower_does_not_require_world_resolution", "item_entity_pickup_laws:exhausted_operation_budget_cannot_install_partial_inventory", "item_entity_pickup_laws:successful_emptying_restores_original_entity_count_and_stat_quantity", "item_entity_pickup_laws:inactive_production_branch_retains_both_actual_owners", "item_entity_pickup_laws:exhausted_production_scan_branch_retains_the_full_ordered_list"];
const allRoots=["item_entity_pickup_laws:refused_candidate_retains_both_complete_affine_owners", "item_entity_pickup_laws:inactive_touch_retains_inventory_and_all_entity_fields", "item_entity_pickup_laws:unadmitted_touch_never_reads_or_installs_inventory", "item_entity_pickup_laws:client_side_item_receiver_is_inactive", "item_entity_pickup_laws:partial_survival_insertion_retains_residue_without_take_or_stats", "item_entity_pickup_laws:discarded_item_retains_original_count_and_nonpickup_fields", "item_entity_pickup_laws:survival_no_progress_keeps_residue_and_false_return", "item_entity_pickup_laws:creative_no_progress_clears_residue_and_returns_true", "item_entity_pickup_laws:unresolved_thrower_refuses_success_publication", "item_entity_pickup_laws:absent_thrower_does_not_require_world_resolution", "item_entity_pickup_laws:exhausted_operation_budget_cannot_install_partial_inventory", "item_entity_pickup_laws:successful_emptying_restores_original_entity_count_and_stat_quantity", "item_entity_pickup_laws:exhausted_scene_scan_retains_entities_player_rng_factory_and_ids", "item_entity_pickup_laws:inactive_production_branch_retains_both_actual_owners", "item_entity_pickup_laws:exhausted_production_scan_branch_retains_the_full_ordered_list"];
const ordinaryOnly=["item_entity_pickup_laws:inactive_touch_retains_inventory_and_all_entity_fields", "item_entity_pickup_laws:unadmitted_touch_never_reads_or_installs_inventory", "item_entity_pickup_laws:exhausted_scene_scan_retains_entities_player_rng_factory_and_ids"];
const selectedRoots=roots;
const sha=x=>crypto.createHash("sha256").update(x).digest("hex");
const book=B.book_nil(),seen=new Map();
await B.book_load(book,entry,"",seen);
const before=Object.fromEntries([...seen.keys()].sort().map(p=>[p,sha(fs.readFileSync(p))]));
B.book_valid(book);
if(book.hols!==0)throw Error("Open proof holes");
const originalOrder=[...book.order],originalTlds=book.tlds,originalCtrs=book.ctrs,originalTmps=book.tmps;
const originals=Object.entries(book.tlds).map(([k,t])=>[k,t,t.T,t.$==="Def"?t.v:null,t.$==="Def"?t.e:null]);
const termPins=selectedRoots.map(k=>{const t=book.tlds[k];if(t?.$!=="Def"||!t.e||!t.v||t.u||t.i)throw Error("Missing checked pure proof "+k);return {name:k,type_sha256:sha(B.term_key(B.term_lower(t.T))),checked_proof_sha256:sha(B.term_key(t.e)),source_body_sha256:sha(B.term_key(B.term_lower(t.v)))};});
book.order=originalOrder.filter((k,i)=>selectedRoots.includes(k)&&originalOrder.lastIndexOf(k)===i);
if(book.order.length!==selectedRoots.length||book.tlds!==originalTlds||book.ctrs!==originalCtrs||book.tmps!==originalTmps)throw Error("Selection changed declaration ownership");
for(const [k,t,T,v,e] of originals)if(book.tlds[k]!==t||t.T!==T||(t.$==="Def"&&(t.v!==v||t.e!==e)))throw Error("Selection altered term "+k);
const manifest={entry,roots:selectedRoots,ordinary_roots:allRoots,ordinary_only_roots:ordinaryOnly,original_root_count:originalOrder.length,selected_root_count:book.order.length,checked_types_and_bodies_unchanged:true,all_original_tlds_ctrs_tmps_retained:true,term_pins:termPins,source_files:[...seen.keys()],ordinary_source_api_check_passed:true};
fs.writeFileSync(dir+"/selection.json",JSON.stringify(manifest,null,2)+"\n");
console.log(JSON.stringify({phase:"checked-root-selection",roots,original_root_count:originalOrder.length}));
const exclusions=Safe.safe_emit(book,dir+"/selected.bendtt");
fs.writeFileSync(dir+"/scope.json",JSON.stringify({exclusions},null,2)+"\n");
console.log(JSON.stringify({phase:"export-complete",bytes:fs.statSync(dir+"/selected.bendtt").size,exclusions}));
if(exclusions.length)process.exitCode=2;

const after=Object.fromEntries([...seen.keys()].sort().map(p=>[p,sha(fs.readFileSync(p))]));
if(JSON.stringify(before)!==JSON.stringify(after))throw Error("Proof source changed during check/export");
fs.writeFileSync(dir+"/source-pins.json",JSON.stringify(after,null,2)+"\n");
