import * as B from "file:///Users/chuah/Documents/ChatGPT/bendex/bend/bend2/bend.ts";
import * as Safe from "file:///Users/chuah/Documents/ChatGPT/bendex/bend/bend2/safe.ts";
import * as fs from "node:fs";
import * as crypto from "node:crypto";
const entry=process.argv.slice(3).find(a=>!a.startsWith("--"))||new URL("../src/item_entity_render_proof.bend", import.meta.url).pathname;
process.on("uncaughtException",e=>{console.error(e?.$==="Err"?B.err_show(e):e);process.exit(1)});
const dir=process.argv[2];
if(!dir)throw Error("Fresh output directory required");
const roots=["item_entity_render_laws:presentation_uses_actual_old_position", "item_entity_render_laws:item_projection_preserves_full_components_and_bob", "item_entity_render_laws:orb_projection_preserves_actual_value", "item_entity_render_laws:snapshot_excludes_simulation_random_and_factory", "item_entity_render_laws:record_projection_preserves_source_sequence", "item_entity_render_laws:unbound_is_a_refusal_and_retains_numerical_owner", "item_entity_render_laws:hidden_record_preserves_numerical_owner", "item_entity_render_laws:exhausted_scan_publishes_no_partial_frame", "item_entity_render_laws:empty_scan_is_a_bound_empty_frame", "item_entity_render_laws:failed_quad_budget_cannot_publish_frame", "item_entity_render_laws:dynamic_light_preserves_texture_tint_and_material", "item_entity_render_laws:transformed_vertex_preserves_actual_uv", "item_entity_render_laws:no_item_copies_produces_no_geometry", "item_entity_render_laws:zero_count_item_stack_is_not_drawn"];
const allRoots=roots;
const ordinaryOnly=[];
const selectedRoots=roots;
const sha=x=>crypto.createHash("sha256").update(x).digest("hex");
const book=B.book_nil(),seen=new Map();
await B.book_load(book,entry,"",seen);
const before=Object.fromEntries([...seen.keys()].sort().map(p=>[p,sha(fs.readFileSync(p))]));
B.book_valid(book);
if(book.hols!==0)throw Error("Open proof holes");
const originalOrder=[...book.order],originalTlds=book.tlds,originalCtrs=book.ctrs,originalTmps=book.tmps;
const originals=Object.entries(book.tlds).map(([k,t])=>[k,t,t.T,t.$==="Def"?t.v:null,t.$==="Def"?t.e:null]);
const termPins=selectedRoots.map(k=>{const t=book.tlds[k];if(t?.$!=="Def"||!t.e||!t.v||t.u||t.i)throw Error("Missing checked pure proof "+k);return {name:k,type_sha256:sha(B.term_key(B.term_lower(t.T))),checked_proof_sha256:sha(B.term_key(t.e)),source_body_sha256:sha(B.term_key(B.term_lower(t.v)))};});
book.order=originalOrder.filter((k,i)=>selectedRoots.includes(k)&&originalOrder.lastIndexOf(k)===i);
if(book.order.length!==selectedRoots.length||book.tlds!==originalTlds||book.ctrs!==originalCtrs||book.tmps!==originalTmps)throw Error("Selection changed declaration ownership");
for(const [k,t,T,v,e] of originals)if(book.tlds[k]!==t||t.T!==T||(t.$==="Def"&&(t.v!==v||t.e!==e)))throw Error("Selection altered term "+k);
const manifest={entry,roots:selectedRoots,ordinary_roots:allRoots,ordinary_only_roots:ordinaryOnly,original_root_count:originalOrder.length,selected_root_count:book.order.length,checked_types_and_bodies_unchanged:true,all_original_tlds_ctrs_tmps_retained:true,term_pins:termPins,source_files:[...seen.keys()],ordinary_source_api_check_passed:true};
fs.writeFileSync(dir+"/selection.json",JSON.stringify(manifest,null,2)+"\n");
console.log(JSON.stringify({phase:"checked-root-selection",roots,original_root_count:originalOrder.length}));
const exclusions=Safe.safe_emit(book,dir+"/selected.bendtt");
fs.writeFileSync(dir+"/scope.json",JSON.stringify({exclusions},null,2)+"\n");
console.log(JSON.stringify({phase:"export-complete",bytes:fs.statSync(dir+"/selected.bendtt").size,exclusions}));
if(exclusions.length)process.exitCode=2;

const after=Object.fromEntries([...seen.keys()].sort().map(p=>[p,sha(fs.readFileSync(p))]));
if(JSON.stringify(before)!==JSON.stringify(after))throw Error("Proof source changed during check/export");
fs.writeFileSync(dir+"/source-pins.json",JSON.stringify(after,null,2)+"\n");
