import * as B from "file:///Users/chuah/Documents/ChatGPT/bendex/bend/bend2/bend.ts";
import * as Safe from "file:///Users/chuah/Documents/ChatGPT/bendex/bend/bend2/safe.ts";
import * as fs from "node:fs";
import * as crypto from "node:crypto";
const entry=new URL("../src/player_block_inside_stuck_proof.bend", import.meta.url).pathname;
const dir=process.argv[2];
if(!dir)throw Error("Fresh output directory required");
const roots=["player_block_inside_stuck_laws:entity_web_replaces_multiplier_and_resets_fall_only", "player_block_inside_stuck_laws:flying_player_keeps_multiplier_and_history_but_clears_ready_impulse", "player_block_inside_stuck_laws:nonzero_impulse_grace_retains_exact_position", "player_block_inside_stuck_laws:excluded_living_berry_cannot_set_stuck_or_require_damage", "player_block_inside_stuck_laws:eligible_berry_overwrites_previous_web_multiplier", "player_block_inside_stuck_laws:refused_damage_cannot_commit_a_stuck_setter", "player_block_inside_stuck_laws:callback_failure_discards_speculation_and_retains_complete_owner", "player_block_inside_stuck_laws:exhausted_query_retains_arbitrary_complete_owner", "player_block_inside_stuck_laws:unresolved_intersection_retains_owner_and_discards_candidate", "player_block_inside_stuck_laws:failed_world_read_retains_world_registry_receiver_history_and_tail", "player_block_inside_stuck_laws:successful_commit_preserves_all_affine_environment_owners", "player_block_inside_stuck_laws:consumed_multiplier_clears_only_multiplier", "player_block_inside_stuck_laws:inactive_success_preserves_raw_multiplier_and_impulse", "player_block_inside_stuck_laws:rejected_stationary_join_retains_full_actual_motion_owner", "player_block_inside_stuck_laws:refused_decoded_callback_retains_owner_after_earlier_callbacks"];
const sha=x=>crypto.createHash("sha256").update(x).digest("hex");
const book=B.book_nil(),seen=new Map();
await B.book_load(book,entry,"",seen);
const before=Object.fromEntries([...seen.keys()].sort().map(p=>[p,sha(fs.readFileSync(p))]));
B.book_valid(book);
if(book.hols!==0)throw Error("Open proof holes");
const originalOrder=[...book.order],originalTlds=book.tlds,originalCtrs=book.ctrs,originalTmps=book.tmps;
const originals=Object.entries(book.tlds).map(([k,t])=>[k,t,t.T,t.$==="Def"?t.v:null,t.$==="Def"?t.e:null]);
const termPins=roots.map(k=>{const t=book.tlds[k];if(t?.$!=="Def"||!t.e||!t.v||t.u||t.i)throw Error("Missing checked pure proof "+k);return {name:k,type_sha256:sha(B.term_key(B.term_lower(t.T))),checked_proof_sha256:sha(B.term_key(t.e)),source_body_sha256:sha(B.term_key(B.term_lower(t.v)))};});
book.order=originalOrder.filter((k,i)=>roots.includes(k)&&originalOrder.lastIndexOf(k)===i);
if(book.order.length!==15||book.tlds!==originalTlds||book.ctrs!==originalCtrs||book.tmps!==originalTmps)throw Error("Selection changed declaration ownership");
for(const [k,t,T,v,e] of originals)if(book.tlds[k]!==t||t.T!==T||(t.$==="Def"&&(t.v!==v||t.e!==e)))throw Error("Selection altered term "+k);
const manifest={entry,roots,original_root_count:originalOrder.length,selected_root_count:book.order.length,checked_types_and_bodies_unchanged:true,all_original_tlds_ctrs_tmps_retained:true,term_pins:termPins,source_files:[...seen.keys()],ordinary_source_api_check_passed:true};
fs.writeFileSync(dir+"/selection.json",JSON.stringify(manifest,null,2)+"\n");
console.log(JSON.stringify({phase:"checked-root-selection",roots,original_root_count:originalOrder.length}));
const exclusions=Safe.safe_emit(book,dir+"/selected.bendtt");
fs.writeFileSync(dir+"/scope.json",JSON.stringify({exclusions},null,2)+"\n");
console.log(JSON.stringify({phase:"export-complete",bytes:fs.statSync(dir+"/selected.bendtt").size,exclusions}));
if(exclusions.length)process.exitCode=2;

const after=Object.fromEntries([...seen.keys()].sort().map(p=>[p,sha(fs.readFileSync(p))]));
if(JSON.stringify(before)!==JSON.stringify(after))throw Error("Proof source changed during check/export");
fs.writeFileSync(dir+"/source-pins.json",JSON.stringify(after,null,2)+"\n");
