import * as B from "file:///Users/chuah/Documents/ChatGPT/bendex/bend/bend2/bend.ts";
import * as Safe from "file:///Users/chuah/Documents/ChatGPT/bendex/bend/bend2/safe.ts";
import * as fs from "node:fs";
import * as crypto from "node:crypto";
const entry=new URL("../src/player_block_inside_sweep_proof.bend", import.meta.url).pathname;
const dir=process.argv[2];
if(!dir)throw Error("Fresh output directory required");
const roots=["player_block_inside_sweep_laws:next_segment_resets_only_local_seen_and_step", "player_block_inside_sweep_laws:duplicate_crossing_does_not_advance_collector_or_visit_trace", "player_block_inside_sweep_laws:vanilla_step_limit_stops_without_work_budget_error", "player_block_inside_sweep_laws:initial_range_keeps_duplicate_visits_but_not_duplicate_keys", "player_block_inside_sweep_laws:actual_air_read_preserves_receiver_and_global_seen", "player_block_inside_sweep_laws:actual_duplicate_read_keeps_callbacks_and_collector_unchanged", "player_block_inside_sweep_laws:callback_refusal_wins_over_later_traversal_failure", "player_block_inside_sweep_laws:deferred_traversal_failure_discards_all_speculative_callbacks", "player_block_inside_sweep_laws:read_budget_refusal_retains_complete_arbitrary_owner", "player_block_inside_sweep_laws:failed_read_retains_world_registry_receiver_history_and_affine_tail", "player_block_inside_sweep_laws:actual_core_refusal_retains_complete_sweep_owner", "player_block_inside_sweep_laws:registry_decode_refusal_retains_every_owned_field", "player_block_inside_sweep_laws:late_callback_service_refusal_discards_prior_effects", "player_block_inside_sweep_laws:successful_sweep_commits_only_receiver_and_history", "player_block_inside_sweep_laws:noncanonical_request_cannot_read_or_commit", "player_block_inside_sweep_laws:authoritative_berry_uses_actual_known_movement_observation", "player_block_inside_sweep_laws:other_authority_berry_uses_actual_old_minus_current", "player_block_inside_sweep_laws:rejected_body_binding_retains_actual_motion_environment", "player_block_inside_sweep_laws:completed_sweep_restores_every_motion_environment_field", "player_block_inside_sweep_laws:existing_refusal_prevents_every_remaining_world_read", "player_block_inside_sweep_laws:earliest_actual_read_refusal_prevents_later_reads", "player_block_inside_sweep_laws:public_motion_join_installs_only_actual_successful_service_result", "player_block_inside_sweep_laws:public_motion_join_preserves_full_owner_on_service_refusal"];
const sha=x=>crypto.createHash("sha256").update(x).digest("hex");
const book=B.book_nil(),seen=new Map();
await B.book_load(book,entry,"",seen);
const before=Object.fromEntries([...seen.keys()].sort().map(p=>[p,sha(fs.readFileSync(p))]));
B.book_valid(book);
if(book.hols!==0)throw Error("Open proof holes");
const originalOrder=[...book.order],originalTlds=book.tlds,originalCtrs=book.ctrs,originalTmps=book.tmps;
const originals=Object.entries(book.tlds).map(([k,t])=>[k,t,t.T,t.$==="Def"?t.v:null,t.$==="Def"?t.e:null]);
const termPins=roots.map(k=>{const t=book.tlds[k];if(t?.$!=="Def"||!t.e||!t.v||t.u||t.i)throw Error("Missing checked pure proof "+k);return {name:k,type_sha256:sha(B.term_key(B.term_lower(t.T))),checked_proof_sha256:sha(B.term_key(t.e)),source_body_sha256:sha(B.term_key(B.term_lower(t.v)))};});
book.order=originalOrder.filter((k,i)=>roots.includes(k)&&originalOrder.lastIndexOf(k)===i);
if(book.order.length!==23||book.tlds!==originalTlds||book.ctrs!==originalCtrs||book.tmps!==originalTmps)throw Error("Selection changed declaration ownership");
for(const [k,t,T,v,e] of originals)if(book.tlds[k]!==t||t.T!==T||(t.$==="Def"&&(t.v!==v||t.e!==e)))throw Error("Selection altered term "+k);
const manifest={entry,roots,original_root_count:originalOrder.length,selected_root_count:book.order.length,checked_types_and_bodies_unchanged:true,all_original_tlds_ctrs_tmps_retained:true,term_pins:termPins,source_files:[...seen.keys()],ordinary_source_api_check_passed:true};
fs.writeFileSync(dir+"/selection.json",JSON.stringify(manifest,null,2)+"\n");
console.log(JSON.stringify({phase:"checked-root-selection",roots,original_root_count:originalOrder.length}));
const exclusions=Safe.safe_emit(book,dir+"/selected.bendtt");
fs.writeFileSync(dir+"/scope.json",JSON.stringify({exclusions},null,2)+"\n");
console.log(JSON.stringify({phase:"export-complete",bytes:fs.statSync(dir+"/selected.bendtt").size,exclusions}));
if(exclusions.length)process.exitCode=2;

const after=Object.fromEntries([...seen.keys()].sort().map(p=>[p,sha(fs.readFileSync(p))]));
if(JSON.stringify(before)!==JSON.stringify(after))throw Error("Proof source changed during check/export");
fs.writeFileSync(dir+"/source-pins.json",JSON.stringify(after,null,2)+"\n");
