import * as B from "file:///Users/chuah/Documents/ChatGPT/bendex/bend/bend2/bend.ts";
import * as Safe from "file:///Users/chuah/Documents/ChatGPT/bendex/bend/bend2/safe.ts";
import * as fs from "node:fs";
import * as crypto from "node:crypto";
const entry=new URL("../src/resource_catalog_world_composition_proof.bend", import.meta.url).pathname;
const dir=process.argv[2];
if(!dir)throw Error("Fresh output directory required");
const roots=["resource_catalog_world_laws:metadata_view_preserves_the_complete_texture_owner", "resource_catalog_world_laws:scene_refuses_another_registry_before_any_binding", "resource_catalog_world_laws:prior_identity_refusal_is_not_replaced_by_frame_or_model_errors", "resource_catalog_world_laws:invalid_frame_refusal_precedes_instance_traversal", "resource_catalog_world_laws:an_empty_instance_suffix_preserves_all_accumulated_geometry", "resource_catalog_world_laws:exhausted_block_budget_refuses_before_catalog_access", "resource_catalog_world_laws:exhausted_binding_budget_refuses_before_catalog_access", "resource_catalog_world_laws:cell_binding_uses_its_explicit_selection_and_appearance", "resource_catalog_world_laws:binding_admission_failure_does_not_advance_the_accumulator", "resource_catalog_world_laws:invalid_origin_retains_the_requested_registry_state", "resource_catalog_world_laws:admitted_cell_extends_the_existing_accumulator", "resource_catalog_world_laws:world_mesh_errors_retain_the_exact_state", "resource_catalog_world_laws:scene_failure_preserves_the_complete_assets_owner", "resource_catalog_world_laws:render_failure_preserves_the_complete_assets_owner", "resource_catalog_world_laws:render_success_preserves_the_complete_assets_owner_and_image", "resource_catalog_world_laws:sprite_metadata_retains_loaded_texture_slot_order", "resource_catalog_world_laws:an_empty_admitted_frame_retains_camera_and_render_settings", "resource_catalog_world_laws:a_zero_shared_quad_budget_refuses_the_next_quad", "resource_catalog_world_load:load_failure_preserves_registry_and_error"];
const sha=x=>crypto.createHash("sha256").update(x).digest("hex");
const book=B.book_nil(),seen=new Map();
await B.book_load(book,entry,"",seen);
const before=Object.fromEntries([...seen.keys()].sort().map(p=>[p,sha(fs.readFileSync(p))]));
B.book_valid(book);
if(book.hols!==0)throw Error("Open proof holes");
const originalOrder=[...book.order],originalTlds=book.tlds,originalCtrs=book.ctrs,originalTmps=book.tmps;
const originals=Object.entries(book.tlds).map(([k,t])=>[k,t,t.T,t.$==="Def"?t.v:null,t.$==="Def"?t.e:null]);
const termPins=roots.map(k=>{const t=book.tlds[k];if(t?.$!=="Def"||!t.e||!t.v||t.u||t.i)throw Error("Missing checked pure proof "+k);return {name:k,type_sha256:sha(B.term_key(B.term_lower(t.T))),checked_proof_sha256:sha(B.term_key(t.e)),source_body_sha256:sha(B.term_key(B.term_lower(t.v)))};});
book.order=originalOrder.filter((k,i)=>roots.includes(k)&&originalOrder.lastIndexOf(k)===i);
if(book.order.length!==19||book.tlds!==originalTlds||book.ctrs!==originalCtrs||book.tmps!==originalTmps)throw Error("Selection changed declaration ownership");
for(const [k,t,T,v,e] of originals)if(book.tlds[k]!==t||t.T!==T||(t.$==="Def"&&(t.v!==v||t.e!==e)))throw Error("Selection altered term "+k);
const manifest={entry,roots,original_root_count:originalOrder.length,selected_root_count:book.order.length,checked_types_and_bodies_unchanged:true,all_original_tlds_ctrs_tmps_retained:true,term_pins:termPins,source_files:[...seen.keys()],ordinary_source_api_check_passed:true};
fs.writeFileSync(dir+"/selection.json",JSON.stringify(manifest,null,2)+"\n");
console.log(JSON.stringify({phase:"checked-root-selection",roots,original_root_count:originalOrder.length}));
const exclusions=Safe.safe_emit(book,dir+"/selected.bendtt");
fs.writeFileSync(dir+"/scope.json",JSON.stringify({exclusions},null,2)+"\n");
console.log(JSON.stringify({phase:"export-complete",bytes:fs.statSync(dir+"/selected.bendtt").size,exclusions}));
if(exclusions.length)process.exitCode=2;

const after=Object.fromEntries([...seen.keys()].sort().map(p=>[p,sha(fs.readFileSync(p))]));
if(JSON.stringify(before)!==JSON.stringify(after))throw Error("Proof source changed during check/export");
fs.writeFileSync(dir+"/source-pins.json",JSON.stringify(after,null,2)+"\n");
