import * as B from "file:///Users/chuah/Documents/ChatGPT/bendex/bend/bend2/bend.ts";
import * as Safe from "file:///Users/chuah/Documents/ChatGPT/bendex/bend/bend2/safe.ts";
import * as fs from "node:fs";
import * as crypto from "node:crypto";
const entry=process.argv.slice(3).find(a=>!a.startsWith("--"))||new URL("../src/vanilla_lightmap_proof.bend", import.meta.url).pathname;
process.on("uncaughtException",e=>{console.error(e?.$==="Err"?B.err_show(e):e);process.exit(1)});
const dir=process.argv[2];
if(!dir)throw Error("Fresh output directory required");
const roots=["vanilla_lightmap_laws:fresh_texture_is_actual_white_and_does_not_draw_random", "vanilla_lightmap_laws:rejected_context_recovers_complete_renderer_and_table_owners", "vanilla_lightmap_laws:rejected_evaluated_uniforms_do_not_clear_dirty_or_replace_texture", "vanilla_lightmap_laws:clean_extract_does_not_draw_rng_read_context_or_change_pixels", "vanilla_lightmap_laws:absent_dirty_extract_retains_rng_flicker_dirty_and_previous_uniforms", "vanilla_lightmap_laws:successful_uniform_commit_preserves_rng_and_clears_dirty", "vanilla_lightmap_laws:hidden_flash_cannot_modify_sky_factor", "vanilla_lightmap_laws:missing_flash_has_no_sky_addition", "vanilla_lightmap_laws:long_or_infinite_night_vision_returns_one_without_table_read", "vanilla_lightmap_laws:invalid_pixel_coordinates_or_uniforms_cannot_publish_rgb", "vanilla_lightmap_laws:black_raw_shader_is_not_claimed_finite", "vanilla_lightmap_laws:observed_black_storage_is_opaque_black", "vanilla_lightmap_laws:nonfinite_shader_output_is_never_integer_quantized"];
const allRoots=roots;
const ordinaryOnly=[];
const selectedRoots=roots;
const sha=x=>crypto.createHash("sha256").update(x).digest("hex");
const book=B.book_nil(),seen=new Map();
await B.book_load(book,entry,"",seen);
const before=Object.fromEntries([...seen.keys()].sort().map(p=>[p,sha(fs.readFileSync(p))]));
B.book_valid(book);
if(book.hols!==0)throw Error("Open proof holes");
const originalOrder=[...book.order],originalTlds=book.tlds,originalCtrs=book.ctrs,originalTmps=book.tmps;
const originals=Object.entries(book.tlds).map(([k,t])=>[k,t,t.T,t.$==="Def"?t.v:null,t.$==="Def"?t.e:null]);
const termPins=selectedRoots.map(k=>{const t=book.tlds[k];if(t?.$!=="Def"||!t.e||!t.v||t.u||t.i)throw Error("Missing checked pure proof "+k);return {name:k,type_sha256:sha(B.term_key(B.term_lower(t.T))),checked_proof_sha256:sha(B.term_key(t.e)),source_body_sha256:sha(B.term_key(B.term_lower(t.v)))};});
book.order=originalOrder.filter((k,i)=>selectedRoots.includes(k)&&originalOrder.lastIndexOf(k)===i);
if(book.order.length!==selectedRoots.length||book.tlds!==originalTlds||book.ctrs!==originalCtrs||book.tmps!==originalTmps)throw Error("Selection changed declaration ownership");
for(const [k,t,T,v,e] of originals)if(book.tlds[k]!==t||t.T!==T||(t.$==="Def"&&(t.v!==v||t.e!==e)))throw Error("Selection altered term "+k);
const manifest={entry,roots:selectedRoots,ordinary_roots:allRoots,ordinary_only_roots:ordinaryOnly,original_root_count:originalOrder.length,selected_root_count:book.order.length,checked_types_and_bodies_unchanged:true,all_original_tlds_ctrs_tmps_retained:true,term_pins:termPins,source_files:[...seen.keys()],ordinary_source_api_check_passed:true};
fs.writeFileSync(dir+"/selection.json",JSON.stringify(manifest,null,2)+"\n");
console.log(JSON.stringify({phase:"checked-root-selection",roots,original_root_count:originalOrder.length}));
const exclusions=Safe.safe_emit(book,dir+"/selected.bendtt");
fs.writeFileSync(dir+"/scope.json",JSON.stringify({exclusions},null,2)+"\n");
console.log(JSON.stringify({phase:"export-complete",bytes:fs.statSync(dir+"/selected.bendtt").size,exclusions}));
if(exclusions.length)process.exitCode=2;

const after=Object.fromEntries([...seen.keys()].sort().map(p=>[p,sha(fs.readFileSync(p))]));
if(JSON.stringify(before)!==JSON.stringify(after))throw Error("Proof source changed during check/export");
fs.writeFileSync(dir+"/source-pins.json",JSON.stringify(after,null,2)+"\n");
